# Generated by Django 5.2.4 on 2025-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_booking_payment_status_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='codemeli',
            field=models.CharField(blank=True, default=1234567890, max_length=10, null=True, verbose_name='کدملی'),
        ),
    ]
